[package]
name = "password_vault"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
rsa = "0.9.6"
rsa_keygen = "1.0.7"
sha2 = "0.10.8"
